apiVersion: v1
kind: Secret
metadata:
  name: never-ending-secrets
  namespace: never-ending
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres.postgres-main.svc.cluster.local:5432/reads"
  TELEGRAM_BOT_TOKEN: "your-telegram-bot-token"
  TELEGRAM_CHANNEL: "your-telegram-channel"
